### PR TITLE
Update to play 2.7

### LINKED ISSUE #550: Not compatible with Play 2.7
With Silhouette 5.0.6 and Play 2.7.0-RC3:

```
java.lang.AbstractMethodError: Method com/mohiva/play/silhouette/api/actions/DefaultSecuredErrorHandler.play$api$http$Status$_setter_$REQUEST_HEADER_FIELDS_TOO_LARGE_$eq(I)V is abstract
	at com.mohiva.play.silhouette.api.actions.DefaultSecuredErrorHandler.play$api$http$Status$_setter_$REQUEST_HEADER_FIELDS_TOO_LARGE_$eq(SecuredAction.scala)
	at play.api.http.Status.$init$(StandardValues.scala:221)
	at com.mohiva.play.silhouette.api.actions.DefaultSecuredErrorHandler.<init>(SecuredAction.scala:299)
	at com.mohiva.play.silhouette.api.actions.SecuredErrorHandlerComponents.securedErrorHandler(SecuredAction.scala:363)
	at com.mohiva.play.silhouette.api.actions.SecuredErrorHandlerComponents.securedErrorHandler$(SecuredAction.scala:363)
```
This comes from new status having been added to the trait `play.api.http.Status` (in [StandardValues](https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/http/StandardValues.scala)).

### PR DESCRIPTION
**Pull request by rfranco**
# Pull Request Checklist

* [x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [x] Have you read through the [contributor guidelines](https://github.com/mohiva/play-silhouette/blob/master/CONTRIBUTING.md)?
* [x] Have you added copyright headers to new files?
* [x] Have you suggest documentation edits?
* [x] Have you added tests for any changed functionality?

## Fixes

Fixes #550

## Purpose

Update to Play 2.7

### CODE REVIEW

**Comment by akkie** [comment]
@rfranco My plan was it to release the next version of Silhouette based on https://github.com/minutemen/silhouette. I see that it's annoying to wait for the next release. So to release the current master with Play 2.7 support makes sense. In the meantime I can polish the Play bindings for Silhouette. Having both versions in parallel would be great. This gives existing users the option to change to Play 2.7 and new users could try out the framework agnostic version.

**Comment by akkie** [comment]
@rfranco The build failed

**Comment by rfranco** [comment]
it's a wierd error
`Exception in thread "specs2-2" java.lang.InternalError: Malformed class name`

I'll test again it.

**Comment by akkie** [comment]
@rfranco I encounter a similar specs2 issue in #551. Maybe there is an issue when using the Play version of specs2 and the standalone version.

**Comment by akkie** [comment]
This seems the issue: https://stackoverflow.com/questions/54920225/nosuchmethoderror-in-mockito-with-specs2

**Comment by rfranco** [comment]
@akkie i tried same Specs2

**Comment by rfranco** [comment]
```

**Comment by rfranco** [comment]
I solved change

`repository.add(any) returns Future.successful(authenticator)`

to 

```repository.add(any) answers { _ => Future.successful(authenticator) }`
or
```
```

**Comment by akkie** [comment]
Maybe @etorreborre has an idea why it fails?

**Comment by akkie** [comment]
@rfranco Could you try to change `any` to `any()` and see if that helps?

**Comment by rfranco** [comment]
@akkie it give same error!

**Comment by rfranco** [comment]
it's 💚

**Comment by rfranco** [comment]
@akkie what is next step to release?

**Comment by akkie** [comment]
@rfranco Will see if I find the time to create a Snapshot release in the next few days. I'll keep you updated

**Comment by akkie** [comment]
I've released a snapshot version. Please report any issues back. I'll release a RC1 in a week if no issues will be reported.

**Comment by nemoo** [comment]
When will the RC1 be released? It would easier to try out the RC1 since it can be tested by adding the dependency via https://mvnrepository.com/artifact/com.mohiva/play-silhouette which obviously does not hold the SNAPSHOT.

**Comment by akkie** [comment]
I've released a RC1

**Pull request merged**
