### PR TITLE
Release version 6.0.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by akkie**

### CODE REVIEW

**Comment by rfranco** [comment]
```

**Comment by akkie** [comment]
@rfranco 

Do you have the snapshot resolver activated?

https://oss.sonatype.org/content/repositories/snapshots/com/mohiva/play-silhouette_2.12/6.0.0-SNAPSHOT/

**Comment by tanacasino** [comment]
@akkie Any updates about 6.0.0 ?
6.0.0-SNAPSHOT works fine for my project and https://github.com/mohiva/play-silhouette-seed/pull/106

**Comment by akkie** [comment]
@tanacasino I'm very busy at the moment. Will see if I release a RC1 today or tomorrow.

**Comment by tanacasino** [comment]
@akkie Thanks! I'm looking forward to 6.0.0 😄

**Pull request merged**
