### PR TITLE
all: Scala 2.13.0 support

### PR DESCRIPTION
**Pull request by ahjohannessen**
- add Scala 2.13.0 support and adjust code to get
   2.11, 2.12 and 2.13 working together.

 - bump dependencies / plugins necessary to get 2.13.0 support.

 - add 2.13.0 to travis ci and ensure that sbt runs with correct
   Scala version.

 - update sbt-runner to [paulp/sbt-extras@0ee2dae](https://github.com/paulp/sbt-extras/commit/0ee2dae2eba72efb4a464a5ad255e348696ecda7)

 - add notes to change log.

### CODE REVIEW

**Comment by akkie** [comment]
@ahjohannessen Awesome :+1: 

Maybe we should use https://github.com/scala/scala-collection-compat?

**Comment by ahjohannessen** [comment]
I considered that, but avoided it due to the extra weight it brings.

**Comment by ahjohannessen** [comment]
@akkie It would be awesome to get a release soon :)

**Comment by akkie** [comment]
@ahjohannessen Thanks :+1: Will release a 6.0.1 in the next few days

**Comment by ahjohannessen** [comment]
Thanks @akkie :)

**Pull request merged**
