### PR TITLE
Scala 2.13 deprecates language.higherKinds so make it a flag for 2.12

### PR DESCRIPTION
**Pull request by nafg**

### CODE REVIEW

**Comment by akkie** [comment]
@nafg Are you sure? The tests fail exactly for 2.13 with the error that higher kinded-types should be enabled.

```
[error] /home/travis/build/mohiva/play-silhouette/silhouette/app/com/mohiva/play/silhouette/api/RequestHandler.scala:47: higher-kinded type should be enabled
[error] by making the implicit value scala.language.higherKinds visible.
[error] ----
[error] This can be achieved by adding the import clause 'import scala.language.higherKinds'
[error] or by setting the compiler option -language:higherKinds.
[error] See the Scaladoc for value scala.language.higherKinds for a discussion
[error] why the feature should be explicitly enabled.
[error] trait RequestHandlerBuilder[E <: Env, +R[_]] extends ExecutionContextProvider {
[error]                                        ^
[error] one error found
[error] (play-silhouette/compile:compileIncremental) Compilation failed
[error] Total time: 81 s, completed Dec 17, 2019 4:12:05 AM
```

**Comment by tanacasino** [comment]
This is Since 2.13.1
https://github.com/scala/scala/blob/3987e83b7cf0af7c8dcb17a08e8a040ccbe9a5e5/src/library/scala/languageFeature.scala#L35-L37

so you need to update to 2.13.1 from 2.13.0

**Comment by nafg** [comment]
See #573

**Comment by akkie** [comment]
Thanks @nafg

**Pull request merged**
