### PR TITLE
fix mohiva/play-silhouette#386

### PR DESCRIPTION
**Pull request by daron666**

### CODE REVIEW

**Comment by akkie** [comment]
I'm not entire happy with the naming of the method. Maybe we can find a solution with only one method for both cases. Let's investigate if this is possible.

**Comment by daron666** [comment]
Yeah. No problem. I'm going to investigate this in nearest future/

**Comment by rfranco** [comment]
the name could be `getAs`

**Comment by akkie** [comment]
@rfranco Great idea! I think the new interface should look like this:
```scala
def getAs[T: ClassTag]: Option[T]

def getByID(id: String): Option[SocialProvider]

def getByIDAs[T <: SocialProvider: ClassTag](id: String): Option[T]

def getSeqAs[T: ClassTag]: Seq[T]
```

Or we use a single method for both ID cases:
```scala
def get[T: ClassTag]: Option[T]

def get[T <: SocialProvider: ClassTag](id: String): Option[T]

def getSeq[T: ClassTag]: Seq[T]
```

But then the user must always give the type to return:
```scala
socialProviderRegistry.get[SocialProvider](provider)
```

What do you think?

**Comment by daron666** [comment]
@akki I like new interface.

**Comment by rfranco** [comment]
@akkie i prefer the second option that give a clean interface

**Comment by akkie** [comment]
I prefer also the second. I'll create a pull request.

**Comment by akkie** [comment]
Fixed with #392

**Pull request closed without merging**
